# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rid_serial_v1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RidSerial(object):
    def setupUi(self, RidSerial):
        RidSerial.setObjectName("RidSerial")
        RidSerial.resize(800, 800)
        self.centralwidget = QtWidgets.QWidget(RidSerial)
        self.centralwidget.setObjectName("centralwidget")
        self.cb_port = QtWidgets.QComboBox(self.centralwidget)
        self.cb_port.setGeometry(QtCore.QRect(100, 20, 150, 25))
        self.cb_port.setObjectName("cb_port")
        self.cb_baudrate = QtWidgets.QComboBox(self.centralwidget)
        self.cb_baudrate.setGeometry(QtCore.QRect(400, 20, 150, 25))
        self.cb_baudrate.setObjectName("cb_baudrate")
        self.lbl_port = QtWidgets.QLabel(self.centralwidget)
        self.lbl_port.setGeometry(QtCore.QRect(20, 20, 71, 17))
        self.lbl_port.setObjectName("lbl_port")
        self.lbl_baudrate = QtWidgets.QLabel(self.centralwidget)
        self.lbl_baudrate.setGeometry(QtCore.QRect(300, 20, 71, 17))
        self.lbl_baudrate.setObjectName("lbl_baudrate")
        self.pb_start_stop = QtWidgets.QPushButton(self.centralwidget)
        self.pb_start_stop.setGeometry(QtCore.QRect(620, 20, 89, 25))
        self.pb_start_stop.setObjectName("pb_start_stop")
        self.tb_result = QtWidgets.QTextBrowser(self.centralwidget)
        self.tb_result.setGeometry(QtCore.QRect(20, 80, 751, 661))
        self.tb_result.setObjectName("tb_result")
        RidSerial.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RidSerial)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        RidSerial.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RidSerial)
        self.statusbar.setObjectName("statusbar")
        RidSerial.setStatusBar(self.statusbar)

        self.retranslateUi(RidSerial)
        QtCore.QMetaObject.connectSlotsByName(RidSerial)

    def retranslateUi(self, RidSerial):
        _translate = QtCore.QCoreApplication.translate
        RidSerial.setWindowTitle(_translate("RidSerial", "RID Serial"))
        self.lbl_port.setText(_translate("RidSerial", "Port"))
        self.lbl_baudrate.setText(_translate("RidSerial", "Baudrate"))
        self.pb_start_stop.setText(_translate("RidSerial", "Start"))
